- label: UAV Fleet
  page: uav/index.html
  submenu:
    - label: Skyáanaa UAV
      page: uav/qt1.html
    - label: Quadroter
      page: uav/qt2.html
    - label: Ground Control Stations
      page: uav/ground-control-stations.html
    - label: Custom Platforms
      page: uav/custom.html
- label: Software
  page: software/index.html
  submenu:
    - label: MDO Tool
      page: software/mdo.html
